events {}

http {
    server {
        listen 80;

        location /api {
            proxy_pass http://backend:8080;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /notification/ {
            proxy_pass http://notification-api:4000/; 
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # --- NEW LOCATION BLOCK FOR GRAFANA ---
        location /grafana/ {
            # Note the trailing slash here is important
            proxy_pass http://grafana:3000/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # --- NEW LOCATION BLOCK FOR PROMETHEUS ---
        location /prometheus/ {
            # Note the trailing slash here is important
            proxy_pass http://prometheus:9090/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # --- NEW LOCATION BLOCK FOR JAEGER ---
        location /jaeger/api/ {
            proxy_pass http://jaeger:16686/api/;
        
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /jaeger/ {
            # Note the trailing slash here is important
            proxy_pass http://jaeger:16686/;
            
            sub_filter '<base href="/"'  '<base href="/jaeger/"';
            sub_filter_once on;
 
            proxy_http_version 1.1;
            proxy_set_header Accept-Encoding "";
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /health {
            return 200 'Backend OK';
            add_header Content-Type text/plain;
        }
    }
}
